{
 "title": "DEV Stake Pool",
 "description": "DEV Stake Pool Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer\"} / cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer\"} * 100)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Luck %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_luck_lifetime{alias=\"relay1\"}*100"
    }
   ]
  },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current Period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry Period"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "bargauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"relay2\"}/432000",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_active_stake{alias=\"relay1\"}/1000000"
    }
   ]
  },
  {
   "title": "Saturation (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_saturated{alias=\"relay1\"}*100",
     "legendFormat": "ADA"
    }
   ]
  },
  {
   "title": "Home Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"devstakepool\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"devstakepool\"} / (node_memory_MemTotal_bytes{alias=\"devstakepool\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"devstakepool\"} / node_memory_SwapTotal_bytes{alias=\"devstakepool\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"devstakepool\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"devstakepool\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Blocks Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blocksForgedNum_int{alias=\"block-producer\"}"
    }
   ]
  },
  {
   "title": "Peers (Relay)",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 9, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rts_gc_wall_ms / (1000)" }
   ]
  },
  {
   "title": "AdaPools.org Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_rank{alias=\"relay1\"}"
    }
   ]
  },
  {
   "title": "Live Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_total_stake{alias=\"relay1\"}/1000000"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay1\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1\"} / (node_memory_MemTotal_bytes{alias=\"relay1\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"relay1\"} / node_memory_SwapTotal_bytes{alias=\"relay1\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Blocks Estimated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_blocks_estimated{alias=\"relay1\"}"
    }
   ]
  },
  {
   "title": "Pledged (ADA)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_pledge{alias=\"relay1\"}/1000000",
     "legendFormat": "ADA"
    }
   ]
  },
  {
   "title": "Missed Slots (Core)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "Missed Slots"
    }
   ]
  },
  {
   "title": "Current ROA % / Lifetime ROA %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_roa{alias=\"relay1\"}"
    },
    {
     "expr": "adapools_roa_lifetime{alias=\"relay1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_delegators{alias=\"relay1\"}"
    }
   ]
  },
  {
   "title": "Fixed cost (ADA) / Margin $",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapools_tax_fix{alias=\"relay1\"}/1000000",
     "legendFormat": "ADA"
    },
    {
     "expr": "adapools_tax_ratio{alias=\"relay1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"relay2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay1\"}",
     "legendFormat": "Relay1"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "System Load (Core Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"devstakepool\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"devstakepool\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"devstakepool\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "System Load (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"relay1\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"relay1\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"relay1\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Network Traffic Basic (Core)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=\"devstakepool\"}[10m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=\"devstakepool\"}[10m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Network Traffic Basic (Realy1)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=\"relay1\"}[10m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{alias=\"relay1\"}[10m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Connected Peers (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int{alias=\"block-producer\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Connected Peers (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_peers_connectedPeers_int{alias=\"relay2\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min) (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"block-producer\"}[150s]) *60",
     "legendFormat": "Core"
    },
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay2\"}[150s]) *60",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min) (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"relay2\"}[150s]) *60",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Time Synchronization (Core Node)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"devstakepool\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"devstakepool\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"devstakepool\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Time Synchronization (Relay Node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"relay1\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"relay1\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"relay1\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  },
  {
   "title": "Memory Utilization (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"devstakepool\"} / (node_memory_MemTotal_bytes{alias=\"devstakepool\"})))* 100",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Memory Utilization (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 55 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1\"} / (node_memory_MemTotal_bytes{alias=\"relay1\"})))* 100",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated (Core Node)",
   "type": "timeseries",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"block-producer\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay2\"}",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated (Relay Node)",
   "type": "graph",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 60 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=\"relay2\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Core Node)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Mempool Transactions (Relay Node)",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 65 },
   "yaxes": [
    { "format": "tx" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay2\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data) (Core Node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"block-producer\"}/(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay2\"}/(1024*1024)",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data) (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 70 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=\"relay2\"}/(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Aggregate Data Transfer (Core Node)",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"devstakepool\"}[1h])) * 3600",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Aggregate Data Transfer (Relay Node)",
   "type": "graph",
   "description": "1 hour rolling window",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{alias=\"relay1\"}[1h])) * 3600",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Max \"Residency\" (Core Node)",
   "type": "timeseries",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"block-producer\"} /(1024*1024)",
     "legendFormat": "Core"
    },
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay2\"} /(1024*1024)",
     "legendFormat": "Relay2"
    }
   ]
  },
  {
   "title": "Max \"Residency\" (Relay Node)",
   "type": "graph",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 80 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=\"relay2\"} /(1024*1024)",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "File Descriptors (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"devstakepool\"}",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "File Descriptors (Relay Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=\"relay1\"}",
     "legendFormat": "Relay"
    }
   ]
  },
  {
   "title": "Disk usage (Core Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{alias=\"devstakepool\"} - node_filesystem_avail_bytes{alias=\"devstakepool\"} ",
     "legendFormat": "Core"
    }
   ]
  },
  {
   "title": "Disk usage (Relay1 Node)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 90 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{alias=\"relay1\"} - node_filesystem_avail_bytes{alias=\"relay1\"} ",
     "legendFormat": "Relay1"
    }
   ]
  }
 ]
}