global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
   - job_name: 'node_exporter'
     static_configs:
       - targets: ['localhost:9100']
         labels:
           alias: 'rpi4'
       - targets: ['devstakepool:9100']
         labels:
           alias: 'devstakepool'
       - targets: ['relay1:9100']
         labels:
           alias: 'relay1' 
   
   - job_name: 'stake-pool'
     static_configs:
       - targets: ['devstakepool:12768']
         labels:
           alias: 'block-producer'
       - targets: ['devstakepool:12788']
         labels:
           alias: 'relay2'
       - targets: ['relay1:12798']
         labels:
           alias: 'relay1'

